### ISSUE TITLE
Configure anzsoil.org redirects

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-asls-substrate#3]
looks like we never asked you to set up redirects for  [http://anzsoil.org/def/au/asls/substrate](http://anzsoil.org/def/au/asls/substrate/genesis) - the vocab is up at https://vocabs.ardc.edu.au/viewById/630 so could you do the usual magic?

**Comment by ljgregory** [comment]
Looks like it has been set up, but has an issue, since this works

http://anzsoil.org/def/au/asls/substrate-browse

Will take a look

**Comment by ljgregory** [comment]
@dr-shorthair , can you please check that the vocab is working as expected - check "view details", it doesn't look like an issue with the redirection

**Comment by dr-shorthair** [comment]
It was an RVA bug - sorry
